# Generated by Django 6.1 on 2026-08-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='manager_remark',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
